USE ACCESSCONTROL
SELECT
    RELAYOUTPT.OUTPUTID - 16 AS Output_Address,
    RELAYOUTPT.NAME AS OutPut_Name,
    ALARMPANEL.NAME AS Board_Name
FROM RELAYOUTPT
JOIN ALARMPANEL ON RELAYOUTPT.PANELID = ALARMPANEL.PANELID
