USE ACCESSCONTROL
SELECT
	AccessPane.NAME as ISC_Name,
	PRODUCTID_VERSION,
	SERIAL_NUMBER,
	DHCP_NAME,
	ACCESSPANE.FIRMWARE_REVISION as Firmware

FROM ACCESSPANE_DIAGNOSTICS

JOIN AccessPane ON ACCESSPANE_DIAGNOSTICS.PANEL_ID = AccessPane.PANELID
ORDER BY AccessPane.NAME
